### ISSUE TITLE
HOT BUG: Kiwix crashes when changing language from Tamil to Kannada

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#28] opened 2014-09-05 09:27 UTC
Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim file - wikipedia_as_all_07_2013.zim 
3. Launch Kiwix and open the above file downloaded in Step 2-wikipedia_as_all_07_2013.zim 
4. Go to Menu->Language and Choose 'Tamil'
5. Provide confirmation to Restart and Kiwix comes up in the changed language 'Tamil'
6. Now follow steps 4 and 5 to change the language to 'Kannada'
7. The application crashes with the below error in xulrunner.exe

Thereafter, Kiwix fails to open and every launch brings up xulrunner.exe with the below error:

XML Parsing Error : error in processing external entity reference  

Location: chrome://main/content/main.xul

Line number :9 , Column:1

%mainDTD;
^

**Comment by kelson42** [comment] 2014-09-06 08:22
Yes. This was a bug which is fixed in new dev version:
http://download.kiwix.org/bin/0.9/

It's already listed in the changelog: http://changelog.kiwix.org

**Comment by kelson42** [comment] 2014-09-12 19:26
I close the bug because this is fixed, was also a duplicate of:
https://github.com/Bug-Bash/selenium-kiwix/issues/18

Thanks again for having reported this problem.
Emmanuel

**Closed as completed by kelson42** 2014-09-12 19:26 UTC
