### ISSUE TITLE
Wiktionary: My Library: There are two distinct downloads of Wiktionary. 

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#4] opened 2014-09-05 08:19 UTC
OS – Windows 8.1
Version - kiwix-0.9-rc2-win
Language - English

**Comment by kelson42** [comment] 2014-09-06 08:11
I can not reproduce it, maybe you have not seen that these wiktionaries are in different languages?

**Comment by aarjay** [comment] 2014-09-06 08:49
Could reproduce on Windows8.1 and Windows 7 ultimate Operating System. 
Please let me know, if you have tried on a different OS. And how the wiktionary was downloaded. Thank you.

**Comment by aarjay** [comment] 2014-09-06 09:41
Please find attached the screenshot.
![wiktionary](https://cloud.githubusercontent.com/assets/5223163/4174805/f7246730-35a9-11e4-93cb-db0e9afc73b5.png)

**Comment by rashiq** [comment] 2014-09-06 12:13
This is weird. 
I could reproduce the same bug (as I suspect). I downloaded the sample Ray Charles zim and suddenly had two entries of it in my library tab:
![bildschirmfoto 2014-09-06 um 14 09 42](https://cloud.githubusercontent.com/assets/1624385/4175096/b7a250f8-35be-11e4-9813-a3c1f9ea8a6d.png)

I checked the `/Users/<user>/Library/Application Support/Kiwix/Profiles/` path, but there was only this one zim file. But the `library.xml` listed the exact same zim file twice.

[Here's](http://pastebin.com/xnWMZrSX) a paste of my `library.xml`. (I've cut out the base64 encoded favicon string.)

**Comment by kelson42** [comment] 2014-09-06 15:35
OK, this is a problem with 0.9rc2 only. Please do it with 0.8 final (soon to be released) and it should work:
http://download.kiwix.org/bin/0.9/

**Comment by aarjay** [comment] 2014-09-08 08:53
Please note: The below issue is already reported as part of another bug. 
Installation of kiwix-0.9-win.zip downloaded from this link http://download.kiwix.org/bin/0.9/ is prevented on Windows 8.1 OS. 
Though this can be by-passed by selecting 'Run anyway'. 
Can we take note of this and let the installation be smooth, without blocking the installation in the first attempt?

**Comment by kelson42** [comment] 2014-09-12 17:42
This is important to deal only with one issue per ticket. If there is an other problem, please report it in a new bug.

What you are reporting about Windows 8.1 seems to be caused by the fact that 0.9rc2 for Windows is not a signed software (digital signature) and we are going to sign any further software we release for OSX and Windows, so this should be easier in the future. In the meantime, simple ignore this warning.

Thank you again for this bug report, I close it because this is now fixed in the furture 0.9 version:
http://download.kiwix.org/bin/0.9/

Regards
Emmanuel

**Closed as completed by kelson42** 2014-09-12 17:42 UTC
