### ISSUE TITLE
User friendliness not observed

### ISSUE THREAD

**Issue by samanway-sprinklr** [bugbash/selenium-kiwix#13] opened 2014-09-05 08:41 UTC
< Suggestion > How will the users know whether the hyperlink is an external link or a zim link ? Obviously, if we do mouse hover over the link we will get to know about it’s type, but the mouse-hovering information may not catch the eye of a naive user. And if he clicks on any external link unknowingly, it would open a new tab in the web browser and it would take the user to the page where actual content is stored in wikipedia. If he’s connected to the internet, well and good, but what if the user is in offline mode, since thats the basic purpose for him/her to download the software to view the wiki contents in offline mode. Then he might be a little clueless about how to go about that. Therefore, an update manager for kiwix zim files will come in handy or there should be a pop-up stating that the link cant be open since it's an external link without internet connection.

**Comment by soloturn** [comment] 2014-09-06 09:22
would a preference help to enable - disable online links?

**Comment by samanway-sprinklr** [comment] 2014-09-06 10:25
Thanks a lot for considering it. Yes a preference would definitely help the end users a lot.

**Comment by kelson42** [comment] 2014-09-17 03:55
Thank you for your feedback. I fully agree that external link should be removed or clearly indicated as external links.

You don't give a us a real example but I guess your experience is based on one of the ZIM file generated on Wikipedia itself (maybe the one about Ray Charles). The problem is tracked here https://bugzilla.wikimedia.org/show_bug.cgi?id=30199. I think this problem will be fixed in the next months.

ZIM files made by the Kiwix project should not suffer of this issue, all external links are marked as external in the same way like on the online version (with a small icon beside).

Regards
Emmanuel

**Closed as completed by kelson42** 2014-09-17 03:55 UTC
