### ISSUE TITLE
All the images related to the content in kiwix are external links

### ISSUE THREAD

**Issue by samanway-sprinklr** [bugbash/selenium-kiwix#16] opened 2014-09-05 08:42 UTC
All the images are external links for contents that can be viewed from kiwix. So ideally if the contents are present in kiwix, images related to that particular content must also be zim links.

**Comment by rashiq** [comment] 2014-09-05 12:12
I agree. Thanks for reporting that! 
@kelson42 can you please take a look at that?

**Comment by kelson42** [comment] 2014-09-05 16:12
@samanway-sprinklr
All image links should be internal links.

Can you please share with us:
- ZIM file name (where do you have download it)
- Article title
- Image URL concerned (and how it should be to your opinion)

... So I can have a look to the problem?

**Comment by samanway-sprinklr** [comment] 2014-09-05 17:26
Dear All,
The zim file downloaded by me was "wikipedia_en_ray_charles_03_2013.zim". The article was about Ray Charles where all the images were external links.

**Comment by samanway-sprinklr** [comment] 2014-09-05 17:27
In my opinion ideally whenever any image is provided in an article it should be an internal link while other hyperlinks may be external.

**Comment by kelson42** [comment] 2014-09-20 13:29
You have a online available version of this ZIM file here:
http://library.kiwix.org/wikipedia_en_ray_charles_03_2013/A/Ray%20Charles

All the displayed images are in the ZIM file itself. Sorry but I don't get the problem.

**Comment by kelson42** [comment] 2014-10-18 15:20
I close this ticket because:
- I can not reproduce the problem
- If there is a problem, this is related to the ZIM file itself and the toolchain to generate this ZIM file is now deprecated (is replaced by Wikimedia OCG toolchain).

@samanway-sprinklr Thank you for taking time to report this and sorry for not being able to provide a quick solution to that.

**Closed as completed by kelson42** 2014-10-18 15:20 UTC
