### ISSUE TITLE
[Mac] "Wikipedia for schools" icon on the home page when clicked on results in Empty page

### ISSUE THREAD

**Issue by ddhamnekar** [bugbash/selenium-kiwix#54] opened 2014-09-05 12:01 UTC
1. Click on the "Wikipedia for schools" icon on home page.
2. It results in Empty/Blank page.

Expected Result: It should not be a clickable field on the Home page as it gets the user back to home page.

**Comment by kelson42** [comment] 2014-09-19 20:32
Thx for your report but this is a duplicate of (or other way, it's a duplicate of your ;)
https://github.com/Bug-Bash/selenium-kiwix/issues/107

**Closed as completed by kelson42** 2014-09-19 20:32 UTC
